<div id="uebermich" class="clearfix">
	<img src="/img/bw.png" alt="Portrait von Barbara Wenger" />
	<div id="ucontent">
		<h1>Über mich</h1>
		<div>
			<span>
				Im Mai 1962 wurde ich in Bad Tölz geboren, wo ich bis heute mit meiner Familie lebe und als Therapeutin arbeite.
				Mein beruflicher Werdegang begann 1984.
			</span>
			<h2>Meine therapeutische Ausbildung in chronologischer Reihenfolge:</h2>
			<ul>
				<li>Ausbildung zur <strong>Masseurin</strong> und <strong>medizinischen Bademeisterin</strong></li>
				<li>Ausbildung zur <strong>Physiotherapeutin</strong></li>
				<li>Fortbildung zur <strong>Sportphysiotherapeutin</strong></li>
				<li>Ausbildung zur <strong>Osteopathin</strong> am Zentrum für Naturheilkunde in München (5 Jahre)</li>
				<li>Weiterbildung zur <strong>Osteopathin für Kinder und Säuglinge</strong></li>
				<li>Seit 2 Jahren in Ausbildung zur <strong>Heilpraktikerin</strong></li>
			</ul>
			<span>
				Durch die Verknüpfung der einzelnen erlernten Behandlungstechniken und die dabei gewonnenen neuen Betrachtungsweisen erschlossen sich mir die gewünschten,
				ganzheitlichen Behandlungsansätze. Daraus resultiert meine integrative Körperarbeit am Patienten.
			</span>
		</div>
	</div>
</div>