<div id="therapie" class="clearfix">
	<div id="osteophatie">
		<h1 class="headerFont">Die Osteopathie erklärt</h1>
		<p>
			<strong>Osteopathie</strong> ist eine eigenständige, ganzheitliche und medizinische Therapie, die unterschiedlichste körperliche Beschwerden lösen oder zumindest reduzieren kann.
			Alle lebensnotwendigen Funktionen stimmt unser Körper in ständiger Bewegung aufeinander ab. Dabei rückt ein Großteil dieser Mobilität nur selten ins Bewusstsein des Menschen,
			vor allem weil unser Körper auf die ständigen inneren und äußeren Einflüsse grundsätzlich sehr anpassungsfähig reagiert.<br/>Der Organismus signalisiert uns daher nicht immer
			über Schmerzen, wenn seine Ausgleichsfähigkeit erschöpft ist. In einer solchen Phase genügt dann schon ein weiterer geringfügiger physischer oder psychischer
			<strong>Stressauslöser</strong> und der Körper "streikt", z. B. in Form eines <strong>Hexenschusses</strong>.<br/>Und hier setzt <strong>Osteopathie</strong> an.
			Denn die Quelle der Beschwerden liegt sehr oft nicht dort, wo zuletzt die Schmerzen auftraten. Der Osteopath gibt dem Gewebe mittels seiner langjährig erlernten Techniken die
			Möglichkeit einer Tiefenentspannung, er stimuliert damit den Selbstheilungsprozess. Der krankmachende Elastizitätsverlust des Gewebes, gleich ob bei Muskeln, Knochen oder
			Organen wird behoben.
		</p>
	</div>
	<div id="craniosacral" class="infobx">
		<h1 class="headerFont">Die craniosacrale Osteopathie</h1>
		<p>
			Bei der <strong>craniosacralen Osteopathie</strong> geht es um die Harmonisierung des <strong>Nervensystems</strong> und des <strong>Flüssigkeitssystems</strong>.<br/><br/>
			Ein Spannungsungleichgewicht innerhalb eines der beiden oder beider Systeme kann zu einer Vielfalt von sensorischen, motorischen und anderen neurologischen Symptomen führen.
			Der <strong>craniosacrale Behandlungsansatz</strong> wirkt durch die direkte Verbindung zum <strong>Nervensystem</strong> und <strong>Flüssigkeitssystem</strong> im Körper
			auf den gesamten Organismus sowie das psychische Gleichgewicht ein.
		</p>
	</div>
	<div id="viszeral" class="infobx">
		<h1 class="headerFont">Die viszerale Osteopathie</h1>
		<p>
			Bei der <strong>viszeralen Osteopathie</strong> geht es um das Lösen, Dehnen und Stimulieren von <strong>Organen</strong>.<br/><br/>
			Die viszerale, <strong>organbezogene Osteopathie</strong> betrifft die <strong>inneren Organe</strong> in ihrem Zusammenhang zum Gesamtorganismus. Viszerale Techniken können
			die Mobilität, die Durchblutung und damit die Funktion <strong>innerer Organe</strong> beeinflussen.<br/>Bewegungseinschränkungen der Organe und damit verbundene Funktionsstörungen
			werden durch sanftes Lösen der bindegewebigen Hüllen (Faszien) der Organe untereinander positiv beeinflusst. Die Aufhängungen werden gedehnt. Die Durchblutungswege stimuliert und
			je nach Bedarf die Nervenversorgung angeregt oder beruhigt.
		</p>
		<p>
			Die <strong>inneren Organe</strong> haben im Körper einen geschützten Bewegungsraum. Sie sind in der Körperwand und/oder an der Wirbelsäule aufgehängt. Von bindegewebigen Hüllen
			umschlossen gleiten sie aneinander und bewegen sich im Zusammenspiel mit den Bewegungen des Körpers und der Atmung.<br/>Die Aufhängungen enthalten die Blut- und Lymphgefäße der Organe
			sowie deren Verbindung zum zentralen Nervensystem. Die Wände der Bauchorgane enthalten zudem ein Nervensystem – umgangssprachlich oft als Bauchhirn bezeichnet- das mit
			dem autonomen Nervensystem kommuniziert.<br/>Die innere Beweglichkeit ist also nicht nur für die Organe selbst wesentlich, sie hat auch Einfluss auf den Bewegungsapparat
			und damit auf die Körperhaltung auf die Atmung, die Durchblutung und den Lymphfluss sowie auf das hormonelle und neurovegetative Gleichgewicht.
		</p>
	</div>
	<div id="parietal" class="infobx">
		<h1 class="headerFont">Die parietale Osteopathie</h1>
		<p>
			Die <strong>muskel- bzw. skelettbezogene Osteopathie</strong> betrifft die Strukturen des Bewegungsapparates: die Knochen, Muskeln, Sehnen, Bänder.
			Die verwandten Techniken haben über neuronale Rückkopplung indirekt Einfluss auf Organfunktionen, Atmung und Durchblutung.
		</p>
	</div>
	<div id="fdm" class="infobx">
		<h1 class="headerFont">Das Faszien-Distorsions-Modell</h1>
        <h2>1. Die FDM-Diagnose allgemein</h2>
		<p>
			Die <strong>FDM-Befundung</strong> basiert auf drei Säulen und führt - neben der schulmedizinischen Diagnose - zu einer eigenständigen FDM-Diagnose.
            Einen besonderen Stellenwert nimmt dabei die Interpretation der Schmerzgestik des Patienten ein. Durch eine spezielle Deutung können diese intuitiven Gesten entschlüsselt werden und geben direkte Hinweise auf Faszienverformungen.
            Eine umfassende Anamnese und Untersuchung ergänzen den Befund des <strong>Faszien-Distorsions-Modell</strong>. Röntgenbilder, Blutuntersuchungen usw. fließen ebenfalls in den Untersuchungsablauf ein.
		</p>
        <h2>2. Die FDM-Behandlung mit der Typaldos-Methode</h2>
        <p>
            Nach Ausschluss etwaiger Kontraindikationen (eine FDM-Behandlung wäre ungeignet) und einer genauen Definition des Behandlungsziels, werden die Faszienverformungen durch gezielte Handgriffe korrigiert.<br/>
            Teilweise wird mit starkem Druck auf bestimmte Punkte oder Bahnen eingewirkt.<br/>
            Andere Distorsionen (Verformungen) werden mit Traktion (Zug) oder Komrpession (Druck) im Bereich von Gelenken verbessert bzw. behoben.<br/>
            Auch flächige Behandlungen bestimmter <strong>Faszien</strong> lindern Beschwerden.
        </p>
        <h2>3. Überprüfung des Behandlungsergebnisses</h2>
        <p>
            Die Behandlung wirkt unmittelbar und kann deshalb vom Patienten sofort beurteilt werden. Bei entsprechendem Erfolg wird die Behandlung fortgesetzt. Eine ausbleibende Wirkung führt zu einer Änderung bzw. Anpassung der Behandlungsmaßnahmen und zur Wiederbefunung des Patienten.
        </p>
	</div>
</div>